name: Perform OCR

on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Update pip
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Perform OCR on PDFs
        run: invoke ocr
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OCR_output
          path: OCR_output.zip
